### ISSUE TITLE
Missing settings.xml file in the root. Error in decision-table quickstart

### ISSUE THREAD

**Issue by anilkmirge** [jboss-developer/jboss-brms-quickstarts#12]
Hello folks,

This is a great start for BRMS 6 - good job. However, I found a problem with your set up. There is no settings.xml file in the root of this quickstarts directory. So, I'm having trouble running the decision-table quickstart. When I ran the mvn clean test -Penable-test,brms command under decision-table quickstart, I get the following:
Non-resolvable import POM: Could not transfer artifact org.jboss.bom.brms:jboss-javaee-6.0-with-drools:pom:6.1.0-build-4 from/to brms-m2-repo (http://localhost:8080/business-central/maven2/) Not authorized , ReasonPhrase:Unauthorized. @ line 67, column 25 -> [Help 2]
[ERROR]     'dependencies.dependency.version' for org.kie:kie-api:jar is missing. @ line 78, column 21
[ERROR]     'dependencies.dependency.version' for org.drools:drools-compiler:jar is missing. @ line 83, column 21
[ERROR]     'dependencies.dependency.version' for org.drools:drools-decisiontables:jar is missing. @ line 89, column 21
[ERROR]     'dependencies.dependency.version' for org.slf4j:slf4j-jdk14:jar is missing. @ line 95, column 21

**Comment by rafabene** [comment]
Hi @anilkmirge 

I've opened this request here: https://issues.jboss.org/browse/JDF-678.

I'll try to add it tomorrow! Thanks for the feedback.

**Comment by anilkmirge** [comment]
That will be awesome. I'm glad to report. Thanks Rafael!
