### ISSUE TITLE
JBoss BRMS & JBoss BPM Suite version does not exist

### ISSUE THREAD

**Issue by eschabell** [jboss-developer/jboss-brms-quickstarts#20]
Hi all,

6.2.0 products not released yet, we are on 6.1.0.GA.

**Comment by psiroky** [comment]
Hello Eric,

I am not sure I understand what you mean. The 6.2.x branch is used for development and early continues integration with latest bits. There is also 6.1.x branch, but that one is no longer maintained.

**Comment by eschabell** [comment]
$ git clone https://github.com/jboss-developer/jboss-brms-quickstarts.git
Cloning into 'jboss-brms-quickstarts'...
remote: Counting objects: 1773, done.
remote: Total 1773 (delta 0), reused 0 (delta 0), pack-reused 1773
Receiving objects: 100% (1773/1773), 458.78 KiB | 0 bytes/s, done.
Resolving deltas: 100% (739/739), done.
Checking connectivity... done.

$ git st
On branch 6.2.x
Your branch is up-to-date with 'origin/6.2.x'.
nothing to commit, working directory clean

$ mvn clean install
[INFO] Scanning for projects...
Downloading: https://maven.repository.redhat.com/ga/org/jboss/bom/brms/jboss-brms-bpmsuite-platform-bom/6.2.0-SNAPSHOT/maven-metadata.xml
Downloading: https://maven.repository.redhat.com/ga/org/jboss/bom/brms/jboss-brms-bpmsuite-platform-bom/6.2.0-SNAPSHOT/jboss-brms-bpmsuite-platform-bom-6.2.0-SNAPSHOT.pom
Downloading: https://maven.repository.redhat.com/ga/org/jboss/bom/brms/jboss-brms-bpmsuite-bom/6.2.0-SNAPSHOT/maven-metadata.xml
Downloading: https://maven.repository.redhat.com/ga/org/jboss/bom/brms/jboss-brms-bpmsuite-bom/6.2.0-SNAPSHOT/jboss-brms-bpmsuite-bom-6.2.0-SNAPSHOT.pom
Downloading: https://maven.repository.redhat.com/ga/org/jboss/bom/eap/jboss-javaee-6.0-with-tools/6.4.3.GA/jboss-javaee-6.0-with-tools-6.4.3.GA.pom
Downloaded: https://maven.repository.redhat.com/ga/org/jboss/bom/eap/jboss-javaee-6.0-with-tools/6.4.3.GA/jboss-javaee-6.0-with-tools-6.4.3.GA.pom (8 KB at 11.6 KB/sec)
Downloading: https://maven.repository.redhat.com/ga/org/jboss/bom/eap/jboss-eap-bom-parent/6.4.3.GA/jboss-eap-bom-parent-6.4.3.GA.pom
Downloaded: https://maven.repository.redhat.com/ga/org/jboss/bom/eap/jboss-eap-bom-parent/6.4.3.GA/jboss-eap-bom-parent-6.4.3.GA.pom (7 KB at 7.8 KB/sec)
Downloading: https://maven.repository.redhat.com/ga/org/jboss/spec/jboss-javaee-6.0/3.0.2.Final-redhat-15/jboss-javaee-6.0-3.0.2.Final-redhat-15.pom
Downloaded: https://maven.repository.redhat.com/ga/org/jboss/spec/jboss-javaee-6.0/3.0.2.Final-redhat-15/jboss-javaee-6.0-3.0.2.Final-redhat-15.pom (18 KB at 19.8 KB/sec)
Downloading: https://maven.repository.redhat.com/ga/org/jboss/jboss-parent/14.0.0.redhat-1/jboss-parent-14.0.0.redhat-1.pom
Downloaded: https://maven.repository.redhat.com/ga/org/jboss/jboss-parent/14.0.0.redhat-1/jboss-parent-14.0.0.redhat-1.pom (0 B at 0.0 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/jboss/jboss-parent/14.0.0.redhat-1/jboss-parent-14.0.0.redhat-1.pom
Downloading: https://maven.repository.redhat.com/ga/org/jboss/arquillian/arquillian-bom/1.1.0.Final/arquillian-bom-1.1.0.Final.pom
Downloading: https://repo.maven.apache.org/maven2/org/jboss/arquillian/arquillian-bom/1.1.0.Final/arquillian-bom-1.1.0.Final.pom
Downloaded: https://repo.maven.apache.org/maven2/org/jboss/arquillian/arquillian-bom/1.1.0.Final/arquillian-bom-1.1.0.Final.pom (11 KB at 119.1 KB/sec)
Downloading: https://maven.repository.redhat.com/ga/org/jboss/shrinkwrap/shrinkwrap-bom/1.1.2/shrinkwrap-bom-1.1.2.pom
Downloading: https://repo.maven.apache.org/maven2/org/jboss/shrinkwrap/shrinkwrap-bom/1.1.2/shrinkwrap-bom-1.1.2.pom
Downloaded: https://repo.maven.apache.org/maven2/org/jboss/shrinkwrap/shrinkwrap-bom/1.1.2/shrinkwrap-bom-1.1.2.pom (4 KB at 43.7 KB/sec)
Downloading: https://maven.repository.redhat.com/ga/org/jboss/arquillian/extension/arquillian-drone-bom/1.1.1.Final/arquillian-drone-bom-1.1.1.Final.pom
Downloading: https://repo.maven.apache.org/maven2/org/jboss/arquillian/extension/arquillian-drone-bom/1.1.1.Final/arquillian-drone-bom-1.1.1.Final.pom
Downloaded: https://repo.maven.apache.org/maven2/org/jboss/arquillian/extension/arquillian-drone-bom/1.1.1.Final/arquillian-drone-bom-1.1.1.Final.pom (6 KB at 65.7 KB/sec)
Downloading: https://maven.repository.redhat.com/ga/org/jboss/arquillian/selenium/selenium-bom/2.29.0/selenium-bom-2.29.0.pom
Downloading: https://repo.maven.apache.org/maven2/org/jboss/arquillian/selenium/selenium-bom/2.29.0/selenium-bom-2.29.0.pom
Downloaded: https://repo.maven.apache.org/maven2/org/jboss/arquillian/selenium/selenium-bom/2.29.0/selenium-bom-2.29.0.pom (6 KB at 26.0 KB/sec)
Downloading: https://maven.repository.redhat.com/ga/org/jboss/bom/brms/jboss-javaee-6.0-with-brms-bpmsuite/6.2.0-SNAPSHOT/maven-metadata.xml
Downloading: https://maven.repository.redhat.com/ga/org/jboss/bom/brms/jboss-javaee-6.0-with-brms-bpmsuite/6.2.0-SNAPSHOT/jboss-javaee-6.0-with-brms-bpmsuite-6.2.0-SNAPSHOT.pom
[ERROR] The build could not read 9 projects -> [Help 1]
[ERROR]  
[ERROR]   The project org.jboss.quickstarts.brms:brms-decision-table:6.2.0-SNAPSHOT (/Users/erics/git-projects/thejbossway/jboss-brms-quickstarts/decision-table/pom.xml) has 6 errors
[ERROR]     Non-resolvable import POM: Could not find artifact org.jboss.bom.brms:jboss-brms-bpmsuite-platform-bom:pom:6.2.0-SNAPSHOT in redhat-product-repo (https://maven.repository.redhat.com/ga) @ line 42, column 25 -> [Help 2]
[ERROR]     'dependencies.dependency.version' for org.kie:kie-api:jar is missing. @ line 52, column 21
[ERROR]     'dependencies.dependency.version' for org.drools:drools-compiler:jar is missing. @ line 57, column 21
[ERROR]     'dependencies.dependency.version' for org.drools:drools-decisiontables:jar is missing. @ line 63, column 21
[ERROR]     'dependencies.dependency.version' for ch.qos.logback:logback-classic:jar is missing. @ line 69, column 21
[ERROR]     'dependencies.dependency.version' for junit:junit:jar is missing. @ line 76, column 21
[ERROR]  
[ERROR]   The project org.jboss.quickstarts.brms:brms-helloworld-bpmsuite:6.2.0-SNAPSHOT (/Users/erics/git-projects/thejbossway/jboss-brms-quickstarts/helloworld-bpmsuite/pom.xml) has 7 errors
[ERROR]     Non-resolvable import POM: Failure to find org.jboss.bom.brms:jboss-brms-bpmsuite-platform-bom:pom:6.2.0-SNAPSHOT in https://maven.repository.redhat.com/ga was cached in the local repository, resolution will not be reattempted until the update interval of redhat-product-repo has elapsed or updates are forced @ line 41, column 25 -> [Help 2]
[ERROR]     'dependencies.dependency.version' for org.kie:kie-api:jar is missing. @ line 51, column 21
[ERROR]     'dependencies.dependency.version' for org.drools:drools-compiler:jar is missing. @ line 56, column 21
[ERROR]     'dependencies.dependency.version' for org.jbpm:jbpm-bpmn2:jar is missing. @ line 64, column 21
[ERROR]     'dependencies.dependency.version' for org.jbpm:jbpm-test:jar is missing. @ line 70, column 21
[ERROR]     'dependencies.dependency.version' for ch.qos.logback:logback-classic:jar is missing. @ line 76, column 21
[ERROR]     'dependencies.dependency.version' for junit:junit:jar is missing. @ line 83, column 21
[ERROR]  
[ERROR]   The project org.jboss.quickstarts.brms:brms-helloworld-brms:6.2.0-SNAPSHOT (/Users/erics/git-projects/thejbossway/jboss-brms-quickstarts/helloworld-brms/pom.xml) has 5 errors
[ERROR]     Non-resolvable import POM: Failure to find org.jboss.bom.brms:jboss-brms-bpmsuite-platform-bom:pom:6.2.0-SNAPSHOT in https://maven.repository.redhat.com/ga was cached in the local repository, resolution will not be reattempted until the update interval of redhat-product-repo has elapsed or updates are forced @ line 41, column 25 -> [Help 2]
[ERROR]     'dependencies.dependency.version' for org.kie:kie-api:jar is missing. @ line 51, column 21
[ERROR]     'dependencies.dependency.version' for org.drools:drools-compiler:jar is missing. @ line 56, column 21
[ERROR]     'dependencies.dependency.version' for ch.qos.logback:logback-classic:jar is missing. @ line 62, column 21
[ERROR]     'dependencies.dependency.version' for junit:junit:jar is missing. @ line 70, column 21
[ERROR]  
[ERROR]   The project org.jboss.quickstarts.brms:brms-helloworld-cep:6.2.0-SNAPSHOT (/Users/erics/git-projects/thejbossway/jboss-brms-quickstarts/helloworld-cep/pom.xml) has 3 errors
[ERROR]     Non-resolvable import POM: Could not find artifact org.jboss.bom.brms:jboss-brms-bpmsuite-bom:pom:6.2.0-SNAPSHOT in redhat-product-repo (https://maven.repository.redhat.com/ga) @ line 52, column 25 -> [Help 2]
[ERROR]     'dependencies.dependency.version' for org.kie:kie-api:jar is missing. @ line 114, column 21
[ERROR]     'dependencies.dependency.version' for org.drools:drools-compiler:jar is missing. @ line 118, column 21
[ERROR]  
[ERROR]   The project org.jboss.quickstarts.brms:brms-helloworld-drl:6.2.0-SNAPSHOT (/Users/erics/git-projects/thejbossway/jboss-brms-quickstarts/helloworld-drl/pom.xml) has 5 errors
[ERROR]     Non-resolvable import POM: Failure to find org.jboss.bom.brms:jboss-brms-bpmsuite-platform-bom:pom:6.2.0-SNAPSHOT in https://maven.repository.redhat.com/ga was cached in the local repository, resolution will not be reattempted until the update interval of redhat-product-repo has elapsed or updates are forced @ line 42, column 25 -> [Help 2]
[ERROR]     'dependencies.dependency.version' for org.kie:kie-api:jar is missing. @ line 52, column 21
[ERROR]     'dependencies.dependency.version' for org.drools:drools-compiler:jar is missing. @ line 57, column 21
[ERROR]     'dependencies.dependency.version' for ch.qos.logback:logback-classic:jar is missing. @ line 63, column 21
[ERROR]     'dependencies.dependency.version' for junit:junit:jar is missing. @ line 71, column 21
[ERROR]  
[ERROR]   The project org.jboss.quickstarts.brms:brms-stateful-ksession:6.2.0-SNAPSHOT (/Users/erics/git-projects/thejbossway/jboss-brms-quickstarts/stateful-ksession/pom.xml) has 3 errors
[ERROR]     Non-resolvable import POM: Failure to find org.jboss.bom.brms:jboss-brms-bpmsuite-bom:pom:6.2.0-SNAPSHOT in https://maven.repository.redhat.com/ga was cached in the local repository, resolution will not be reattempted until the update interval of redhat-product-repo has elapsed or updates are forced @ line 54, column 25 -> [Help 2]
[ERROR]     'dependencies.dependency.version' for org.kie:kie-api:jar is missing. @ line 116, column 21
[ERROR]     'dependencies.dependency.version' for org.drools:drools-compiler:jar is missing. @ line 120, column 21
[ERROR]  
[ERROR]   The project org.jboss.quickstarts.brms:brms-store-brms:6.2.0-SNAPSHOT (/Users/erics/git-projects/thejbossway/jboss-brms-quickstarts/store-brms/pom.xml) has 5 errors
[ERROR]     Non-resolvable import POM: Failure to find org.jboss.bom.brms:jboss-brms-bpmsuite-platform-bom:pom:6.2.0-SNAPSHOT in https://maven.repository.redhat.com/ga was cached in the local repository, resolution will not be reattempted until the update interval of redhat-product-repo has elapsed or updates are forced @ line 43, column 25 -> [Help 2]
[ERROR]     'dependencies.dependency.version' for org.kie:kie-api:jar is missing. @ line 53, column 21
[ERROR]     'dependencies.dependency.version' for org.drools:drools-compiler:jar is missing. @ line 58, column 21
[ERROR]     'dependencies.dependency.version' for ch.qos.logback:logback-classic:jar is missing. @ line 64, column 21
[ERROR]     'dependencies.dependency.version' for junit:junit:jar is missing. @ line 72, column 21
[ERROR]  
[ERROR]   The project org.jboss.quickstarts.brms:brms-tasks-bpmsuite:6.2.0-SNAPSHOT (/Users/erics/git-projects/thejbossway/jboss-brms-quickstarts/tasks-bpmsuite/pom.xml) has 7 errors
[ERROR]     Non-resolvable import POM: Failure to find org.jboss.bom.brms:jboss-brms-bpmsuite-platform-bom:pom:6.2.0-SNAPSHOT in https://maven.repository.redhat.com/ga was cached in the local repository, resolution will not be reattempted until the update interval of redhat-product-repo has elapsed or updates are forced @ line 43, column 25 -> [Help 2]
[ERROR]     'dependencies.dependency.version' for org.kie:kie-api:jar is missing. @ line 53, column 21
[ERROR]     'dependencies.dependency.version' for org.drools:drools-compiler:jar is missing. @ line 58, column 21
[ERROR]     'dependencies.dependency.version' for org.jbpm:jbpm-bpmn2:jar is missing. @ line 65, column 21
[ERROR]     'dependencies.dependency.version' for org.jbpm:jbpm-test:jar is missing. @ line 71, column 21
[ERROR]     'dependencies.dependency.version' for ch.qos.logback:logback-classic:jar is missing. @ line 78, column 21
[ERROR]     'dependencies.dependency.version' for junit:junit:jar is missing. @ line 84, column 21
[ERROR]  
[ERROR]   The project org.jboss.quickstarts.brms:brms-business-resource-planner:6.2.0-SNAPSHOT (/Users/erics/git-projects/thejbossway/jboss-brms-quickstarts/business-resource-planner/pom.xml) has 16 errors
[ERROR]     Non-resolvable import POM: Could not find artifact org.jboss.bom.brms:jboss-javaee-6.0-with-brms-bpmsuite:pom:6.2.0-SNAPSHOT in redhat-product-repo (https://maven.repository.redhat.com/ga) @ line 52, column 25 -> [Help 2]
[ERROR]     Non-resolvable import POM: Failure to find org.jboss.bom.brms:jboss-brms-bpmsuite-platform-bom:pom:6.2.0-SNAPSHOT in https://maven.repository.redhat.com/ga was cached in the local repository, resolution will not be reattempted until the update interval of redhat-product-repo has elapsed or updates are forced @ line 61, column 25 -> [Help 2]
[ERROR]     'dependencies.dependency.version' for javax.enterprise:cdi-api:jar is missing. @ line 75, column 21
[ERROR]     'dependencies.dependency.version' for org.jboss.spec.javax.servlet:jboss-servlet-api_3.0_spec:jar is missing. @ line 82, column 21
[ERROR]     'dependencies.dependency.version' for org.jboss.spec.javax.annotation:jboss-annotations-api_1.1_spec:jar is missing. @ line 89, column 21
[ERROR]     'dependencies.dependency.version' for org.jboss.spec.javax.ws.rs:jboss-jaxrs-api_1.1_spec:jar is missing. @ line 96, column 21
[ERROR]     'dependencies.dependency.version' for org.jboss.spec.javax.ejb:jboss-ejb-api_3.1_spec:jar is missing. @ line 104, column 21
[ERROR]     'dependencies.dependency.version' for org.jboss.spec.javax.faces:jboss-jsf-api_2.1_spec:jar is missing. @ line 112, column 21
[ERROR]     'dependencies.dependency.version' for org.kie:kie-api:jar is missing. @ line 119, column 21
[ERROR]     'dependencies.dependency.version' for org.drools:drools-compiler:jar is missing. @ line 123, column 21
[ERROR]     'dependencies.dependency.version' for org.optaplanner:optaplanner-core:jar is missing. @ line 130, column 21
[ERROR]     'dependencies.dependency.version' for org.optaplanner:optaplanner-benchmark:jar is missing. @ line 134, column 21
[ERROR]     'dependencies.dependency.version' for ch.qos.logback:logback-classic:jar is missing. @ line 139, column 21
[ERROR]     'dependencies.dependency.version' for org.apache.commons:commons-lang3:jar is missing. @ line 144, column 21
[ERROR]     'dependencies.dependency.version' for junit:junit:jar is missing. @ line 153, column 21
[ERROR]     'dependencies.dependency.version' for org.mockito:mockito-all:jar is missing. @ line 158, column 21
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

Broken out of the box?

**Comment by psiroky** [comment]
Quicstarts depend on BOMs https://github.com/jboss-developer/jboss-brms-boms. The SNAPSHOTs  are not being uploaded into any repository right now, so you would need to build them yourself locally. For released product versions (like 6.1.0.GA), they are available in the Red Hat product repo, so you won't encounter the issue there.

I will create contributors-README file and add a note there about the BOMs. I will also look at how EAP does things as it would be ideal to have this working OOTB.

**Comment by eschabell** [comment]
Closing this out.
